### PR TITLE
Test

### PR DESCRIPTION
**Pull request by brotkrume**
test

### CODE REVIEW

**Comment by brotkrume** [comment]
sorry, my fault

**Comment by ephes** [comment]
Well, it kind of worked - seems you have fork running and are able to create pull requests. That's cool!

**Comment by brotkrume** [comment]
Yes, many thanks for the fix. And sorry for the stupid pull request :( I'm new in github and currently trying to fix an encoding issue fetching kptncook receipts...

**Comment by ephes** [comment]
No problem, I know this whole git / GitHub stuff is not easy - take your time.  I'm always happy if someone makes the effort / has the courage to open a PR 😅.

**Pull request closed without merging**
