### PR TITLE
Export to paprika recipe manager

### PR DESCRIPTION
**Pull request by luebbert42**
Hi Jochen,

this code picks one recipe from the local repo and creates the format required by Paprika Recipe Manager (in German right now).
This is basically a gz of a json file, which has to be  wrapped in a zip file. 

Maybe you are interested to merge..

Viele Grüße aus Köln
Dorthe

### CODE REVIEW

**Comment by ephes** [comment]
Hi Dorthe,

wow, this looks great 😃! Now I finally have an excuse to play around with [Paprika](https://www.paprikaapp.com/). I just tried an export and it worked. Maybe it's also possible to export all of the recipes?

There are some minor changes I'd like to add to your PR (httpx instead of requests because of mypy, avoid making http calls in the tests), but I would definitely like to merge it. Thanks a lot!

Viele Grüße aus Düsseldorf
Jochen

**Comment by luebbert42** [comment]
Exporting all recipes is pretty easy. You just have to create multiple gz files and wrap that into a zip file. Do you want me to add this ("if user does not add oid as parameter then export everything")?

Paprika seems to use the uuid to determine if it has to update an existing recipe or create a new entry. Right now I am creating a uuid each time I am exporting. For experting everything I would test if I could take the kpncook oid (which is static). So it would be a kind of "sync" and you could export multiple times everything and only the new recipes would be created in Paprika (bad luck if you changed stuff in Paprika though).

And: I am happy to see your changes, I actually learned a lot from your code (e.g. I did not know flit yet). :-)

**Comment by ephes** [comment]
> Exporting all recipes is pretty easy. You just have to create multiple gz files and wrap that into a zip file. Do you want me to add this ("if user does not add oid as parameter then export everything")?

Sounds great!

> Paprika seems to use the uuid to determine if it has to update an existing recipe or create a new entry. Right now I am creating a uuid each time I am exporting. For experting everything I would test if I could take the kpncook oid (which is static). So it would be a kind of "sync" and you could export multiple times everything and only the new recipes would be created in Paprika (bad luck if you changed stuff in Paprika though).

In the `sync_with_mealie` command I use the same method to find out whether a recipe was already added to mealie. 
 
> And: I am happy to see your changes, I actually learned a lot from your code (e.g. I did not know flit yet). :-)

Thanks :), I didn't know about flit until last year, too. Do you know about [pre-commit](https://pre-commit.com/) hooks? They are configured via `.pre-commit-config.yaml` and they do some checks and linting + autoformat via black and isort. I use them in all my newer projects.

**Comment by luebbert42** [comment]
just a quick update: I worked on the "export all recipes" mini-feature, it's almost done. I am still working on how to correctly do a 404 test with httpx and pytest-mock (sometimes linked images from the kptncook recipes do not longer exist at Cloudfround). To be continued.

**Review by ephes — APPROVED** [review]
Looks really good!

Thanks a lot again for your PR 😀 and pointing me to [Paprika](https://www.paprikaapp.com/)

**Comment by ephes** [comment]
Just released [0.0.10](https://pypi.org/project/kptncook/0.0.10/) 🥳

**Pull request merged**
